### ISSUE TITLE
Crashes when loading synced values

### ISSUE THREAD

**Issue by Lej77** [piroor/webextensions-lib-configs#3]
Currently there is a type on [line 115](https://github.com/piroor/webextensions-lib-configs/blob/master/Configs.js#L115) that causes the library to crash if a sync value is loaded.

The code:
```JavaScript
this[key] = syncedValues[key];
```
should probably be something like:
```JavaScript
values[key] = syncedValues[key];
```

This issue is probably responsible for [Tree Style Tab #1850](https://github.com/piroor/treestyletab/issues/1850) and [Tree Style Tab #1823](https://github.com/piroor/treestyletab/issues/1823).

**Comment by piroor** [comment]
Thanks. After researching, I realized that needless "updated" message is notified to listeners when same value is synchronized from the server. After the commit 70352cda977ba75b4a670b247f1c7f8de04713cf TST won't call listeners for changed configs in this case.

> The code:
> 
> > this[key] = syncedValues[key];
> 
> should probably be something like:
> 
> > values[key] = syncedValues[key];

I don't think so, because `storage.sync.get()` may be processed with delay. The code aims to apply synchronized values after all initialization processes are done.

**Comment by Lej77** [comment]
Thanks, seems fixed now.
